name: Management AWS Lambda Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check changes in lambda directry
        id: check_changes
        run: |
          echo "Changes found in lambda directory."
          echo "changes-detected=false" >> $GITHUB_OUTPUT

      - name: configure-aws-credentials
        if: ${{ steps.check_changes.outputs.changes-detected == 'true' }}
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        if: ${{ steps.check_changes.outputs.changes-detected == 'true' }}
        run: aws sts get-caller-identity

      - name: setup-node
        if: ${{ steps.check_changes.outputs.changes-detected == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: lambda update
        if: ${{ steps.check_changes.outputs.changes-detected == 'true' }}
        run: |
          pip3 install awscli
          cd lambda && zip -r package.zip ./*
          aws lambda update-function-code --function-name lambda-function --zip-file fileb://package.zip --publish
