name: Management AWS Lambda Deploy
on:
  push:
    branches:
      - main
env:
  CHANGES: false
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 最新のコミットとその1つ前のコミットをフェッチする

      - name: check changes in lambda directory
        id: check_changes
        run: |
          git fetch
          DIFF=$(git diff --name-only HEAD^ HEAD -- 'lambda')

          if [ "$DIFF" != "" ]; then
            echo "フォルダ内で変更が見つかりました。"
            echo "CHANGES=true" >> $GITHUB_ENV # changesをtrueに変更する
          else
            echo "フォルダ内で変更が見つかりませんでした。"
          fi
          echo "CHANGESの値は${{env.CHANGES}}です"

      - name: configure-aws-credentials
        if: ${{ env.CHANGES == 'true' }}
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        if: ${{ env.CHANGES == 'true' }}
        run: aws sts get-caller-identity

      - name: setup-node
        if: ${{ env.CHANGES == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: lambda update
        if: ${{ env.CHANGES == 'true' }}
        run: |
          pip3 install awscli
          cd lambda && zip -r package.zip ./*
          aws lambda update-function-code --function-name lambda-function --zip-file fileb://package.zip --publish
