name: AWS Lambda Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Check for changes in lambda directory
        id: check_changes
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          cat changes.txt
          if grep -q "^lambda/" changes.txt; then
            echo "Changes found in lambda directory."
            echo "::set-output name=changes-detected::true"
          else
            echo "No changes in lambda directory."
            echo "::set-output name=changes-detected::false"

      - name: Deploy to AWS Lambda
        if: steps.check_changes.outputs.changes-detected == 'true'
        run: |
          name: configure-aws-credentials
          uses: aws-actions/configure-aws-credentials@master
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: lambda update
        run: |
          pip3 install awscli
          cd lambda && zip -r package.zip ./*
          aws lambda update-function-code --function-name lambda-function --zip-file fileb://package.zip --publish
